### ISSUE TITLE
propel:form:generate fails for separated scheme

### ISSUE THREAD

**Issue by smirik** [propelorm/PropelBundle#173]
Hello,

Environment: symfony 2.1 RC1, FOSUserBundle, propel.

I've created table "profiles" with foreign key user_id related to fos_user table (one-to-one). But when I tried command `php app/console propel:form:generate @ThisIsBundle Profile` I got the following error:

    [BuildException]                                                         
    Table "profiles" contains a foreign key to nonexistent table "fos_user"

I copied the data from FOSUserBundle's schema.xml to the new one and everything was fine after that.
Seems the issue is that in FormGenerateCommand.php at line 55 propel gets info from only one bundle:

    if ($schemas = $this->getSchemasFromBundle($this->bundle)) {

One of the possible solutions is to get all schema.xml files from all bundles and combine them.

Thank you!

**Comment by morozow** [comment]
Sep, 2015... Problem has not solved yet.
