### ISSUE TITLE
Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by tonivdv** [propelorm/PropelBundle#177]
Hello,

I'm trying to make a test with a database applying the instructions from the [propel site](http://www.propelorm.org/cookbook/symfony2/testing.html#the_propel_webtestcase)  but I always get the error _Invalid catalog name: 1046 No database selected_!

I debugged the code a little bit and it works when I comment following part of the code:

``` php
protected static function runCommand($command)
{
    $command = sprintf('%s --quiet', $command);

    return self::getApplication();//->run(new \Symfony\Component\Console\Input\StringInput($command));
}
```

The test I'm trying to run is:

``` php
class ATest extends DatabaseWebTestCase {

  /**
   * @test
   */
  public function test() {

    $test = new \Something\Model\Test();
    $test 
      ->setValue("test")
      ->save();
  }
```

Any idea's if this is an issue, or if I'm doing something completely wrong?

Thx in advance

**Comment by AhmedSamy** [comment]
Solved this problem by the following workaround 

to run
```php
\Propel::setConfiguration($this->getContainer()->get('propel.configuration'));
\Propel::initialize();
```
before 
```php
\Propel::getConnection();
```

**Comment by davyrolink** [comment]
I had a similar setup as @ClementGautier running a sequence of 4 commands in a single process.
````
propel:database:drop --force
propel:database:create
propel:sql:insert --force
propel:fixtures:load
````
I think the first command is deselecting the database, and the second command doesn't re-select it, thus causing the "1046 No database selected" error message. 

I use the following workaround:
````
propel:table:drop --force
propel:sql:insert --force
propel:fixtures:load
````
