### ISSUE TITLE
Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16

### ISSUE THREAD

**Issue by arashdalir** [propelorm/PropelBundle#222]
I just uploaded my symfony app on a server and used "composer update" to get all the vendor packages. seems there's a small problem with the new version of Propel bundle: there's no "om" and "map" folders in it, but the "propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php" depends on the "Propel\PropelBundle\Model\Acl\om\BaseEntryPeer".
as said in propel documentation, i'm using "propel/propel-bundle": "1.1.*" in composer.json to  get the propel bundle.
have I done something wrong?

**Comment by Lionel09** [comment]
env SF2.7 / Propel 1.6

this problem seems to occurs again

```
me@server:~/$ app/console propel:acl:init
PHP Fatal error:  Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /var/www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16
```
