### ISSUE TITLE
Dumping then Loading Fixtures with Foreign Keys

### ISSUE THREAD

**Issue by liamsorsby** [propelorm/PropelBundle#313]
When using propel:fixtures:dump to create the fixtures file.

I've then run propel:build --insert-sql to rebuild the sql and the model. Which successfully rebuilt the model and SQL.

I've then run propel:fixures:load which starts to load the file in however when it gets to foreign keys it throws the following error:

    Unable to execute INSERT statement [INSERT INTO `ProductCategory` (`id`, `ProductID`, `CategoryID`) VALUES (:p0, :p1, :p2)] [wrapped: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`, `ProductCategory`, CONSTRAINT `ProductCategory_FK_1` FOREIGN KEY (`CategoryID`) REFERENCES `Category` (`id`) ON DELETE CASCADE)] 

The pastebin for the schema for the 3 tables: http://pastebin.com/n3cmVCXS
The pastebin for the Fixtures that were exported using propel:fixtures:dump: http://pastebin.com/F8evhHEv

**Comment by havvg** [comment]
I just tried it with an M:N relation, and it worked as expected. The pastebins have expired. If you still encounter the issue, let me know!

**Comment by liamsorsby** [comment]
@havvg, 

The issue only occurred with fixtures when objects are used.
