### ISSUE TITLE
`propel:build` broken for multiple datasources

### ISSUE THREAD

**Issue by alanbem** [propelorm/PropelBundle#325]
An explanation can be found [here](https://github.com/propelorm/PropelBundle/pull/296#issuecomment-74393807)

**Comment by shane-l** [comment]
I think the fix would be to use the same checks that `Propel::getDefaultDB` does i.e use `is_scalar` to check if the connection details are just an alias.

```php
 foreach ($propelConfiguration['datasources'] as $name => $datasource) {
    if (is_scalar($datasource)) {
        // connection details are an alias, ignore
        continue;
    }

    $xml .= strtr(<<<EOT
    // etc
````

**Comment by alanbem** [comment]
Hmmmm, it would require that check in every place that iterates over `datasources`. I don't think it is best solution.

**Comment by shane-l** [comment]
Well the other option is to patch Propel itself and change how `Propel::getDefaultDB` works. Looks like it broke in d970aff.
