### ISSUE TITLE
Support new directory structure

### ISSUE THREAD

**Issue by gharlan** [propelorm/PropelBundle#328]
I think when using symfony 2.x with new (3.0) directory structure (`SENSIOLABS_ENABLE_NEW_DIRECTORY_STRUCTURE`) the migration/fixture/sql files should go to `var/propel` instead of `app/propel`.

Should we locate the `composer.json` and look for the new `extra.symfony-var-dir` setting or what would be the best solution for this?

**Comment by havvg** [comment]
What's the benefit of it? As far as I can see, var only contains removable content, such as cache and log files. I don't see a point in moving the generated and permanently required stuff into var?

I'm on the thought, the `var` directory is never in version control and always cleaned up on deployments, am I wrong here?

**Comment by gharlan** [comment]
After more thought, I agree.
