### ISSUE TITLE
Location of schema.xml (outside of bundle)

### ISSUE THREAD

**Issue by gharlan** [propelorm/PropelBundle#330]
At the moment the `schema.xml` has to be in `<bundle>/Resources/config` (correct me if I'm wrong).
But I think `/app/config/schema.xml` should also be considered.

According to the [Symfony Best Practices](http://symfony.com/doc/current/best_practices/index.html) there should be [only one bundle](http://symfony.com/doc/current/best_practices/creating-the-project.html#application-bundles) for the application logic (called `AppBundle`) and the global resources should be located in `/app` (e.g. [templates](http://symfony.com/doc/current/best_practices/templates.html#template-locations) and [translation files](http://symfony.com/doc/current/best_practices/i18n.html#translation-source-file-location)).

**Comment by Maxooo** [comment]
Now, the question is : is the schema.xml (or another propel schema file name) a global resource ? To initiate the reflexion we can look at the Doctrine ORM implementation in Symfony2. The schema definition doesn't require any "configuration" file and it lies in the classes themselves (stored in a bundle).
Even if you store your schema definition file in the `app` directory you will have to specify the path where you want to store the model classes : in a Bundle...
So, I think the schema.xml file is not a configuration file but a definition file attached to a specific Bundle or the most global application Bundle : the `AppBundle`.
I understand the idea and the goal, but don't know if it's a real good idea. I'm also interested in knowing your point of view.

**Comment by havvg** [comment]
As no bundle is required at all, I'm +1 on enabling support for global schema files. Currently I'm putting them into one bundle, so they are at least in one place :)

It's especially useful, if your models do not live inside a bundle.
