### ISSUE TITLE
PropelBundle 1.4.5 and Propel 1.7.1 on Symfony 2.4 composer fail

### ISSUE THREAD

**Issue by tayhimself** [propelorm/PropelBundle#334]
Hi,
I have a mature project that has been on Symfony 2.4 for a while, no schema.xml or database changes recently.

Unfortunately, like an idiot I seem to have screwed up my project by running a composer update. The composer update can't seem to run the post-update scripts because a path is clearly wrong in the update scripts.. 
![screen shot](https://cloud.githubusercontent.com/assets/1234243/7006977/95e6b792-dc53-11e4-9139-2829179dc467.png)

If I manually fix this using _ln -s_ propel:model:build --verbose fails with no details error. Is there some way to find out what is going on? Any hints to logs etc would be helpful. This is pretty horrifying in terms of usability. Should i upgrade to Symfony 2.7 or something and retry? Is there a supported Propel1 version?

**Comment by marcj** [comment]
Call `php app/console cache:clear --no-warmup -vvv`. with `-vvv`you should get more information.

**Comment by tayhimself** [comment]
Hi marc - first off thanks for responding so quickly.  `php app/console cache:clear --no-warmup -vvv`
gives the same sort of error.
 
Warning: require_once(/Users/salimqadri/git/crash/app/../vendor/propel/runtime/lib/Propel.php): failed to open stream: No such file or directory in /Users/salimqadri/git/crash/vendor/propel/propel-bundle/Propel/PropelBundle/PropelBundle.php on line 29

Fatal error: require_once(): Failed opening required '/Users/salimqadri/git/crash/app/../vendor/propel/runtime/lib/Propel.php' (include_path='/Users/salimqadri/git/crash/vendor/phing/phing/classes:/Users/salimqadri/git/crash/vendor/propel/propel1/runtime/lib:/Users/salimqadri/git/crash/vendor/propel/propel1/generator/lib:.:') in /Users/salimqadri/git/crash/vendor/propel/propel-bundle/Propel/PropelBundle/PropelBundle.php on line 29

If I manually link the `runtime` directory I can continue but then the `propel:model:build` command fails with no information.

**Comment by tayhimself** [comment]
Fixed this ages ago, but just as an FYI in case someone else has a a weird problem like this, the fix was in the **settings.yml** file 

    path:       "%kernel.root_dir%/../vendor/propel"
needed to be changed to

    path:       "%kernel.root_dir%/../vendor/propel/propel1"
