### ISSUE TITLE
propel1 w. sf2.7

### ISSUE THREAD

**Issue by Lionel09** [propelorm/PropelBundle#343]
hello,

i'm starting big migrations stuff from sf2.3 to sf2.7 but i have to keep propel1 for now - hope to migrate to propel2 after this first step will success.

my composer.json looks like:
```
    "require": {
        "php": ">=5.3.9",
        
        "symfony/symfony": "2.7.*",

        "propel/propel-bundle": "1.4.*",
        "willdurand/propel-typehintable-behavior": "1.0.4",
        "craftyshadow/propel-equalnest-behavior": "~1.2",
    },
```

after doing the ```composer update```, i've got a problem with Propel ACL:
```
PHP Fatal error:  Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16
```

And yes, the subdirectories "om" and "map" does not exist, althought the base class are there.

**Comment by havvg** [comment]
You need to generate those classes, those are not checked into version control on purpose.

**Comment by Lionel09** [comment]
thanks

**Comment by Lionel09** [comment]
Actually, none of these 2 commands works:

```
lionel@AcerLio:~/www/myproject$ app/console propel:model:build
PHP Fatal error:  Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /home/lionel/www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16

Fatal error: Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /home/lionel/www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16
lionel@AcerLio:~/www/myproject$ app/console propel:acl:init
PHP Fatal error:  Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /home/lionel/www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16

Fatal error: Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found in /home/lionel/www/myproject/vendor/propel/propel-bundle/Propel/PropelBundle/Model/Acl/EntryPeer.php on line 16
```

I had to copy/paste the base & om folder from another project to make it works.

Any idea?

**Comment by havvg** [comment]
You should copy the schema of the ACL into your `AppBundle`, see https://github.com/propelorm/PropelBundle/issues/209#issuecomment-14031523

**Comment by havvg** [comment]
I think the best solution would be a separation of the bundles. So one may have `PropelAclBundle`, which comes with the `schema.xml` in the right place etc., but still being able to enable/disable the feature as you would disable the bundle completely.

**Comment by Lionel09** [comment]
> You should copy the schema of the ACL into your AppBundle, see #209 (comment)

doesn't seem to change anything, always the same ```PHP Fatal error:  Class 'Propel\PropelBundle\Model\Acl\om\BaseEntryPeer' not found```, it seems the error is prior to the Command execution

**Comment by havvg** [comment]
I just tried it within a new project and it works as expected. The steps I took:

<img width="1280" alt="screen shot 2016-01-23 at 15 27 57" src="https://cloud.githubusercontent.com/assets/126898/12530659/f5a855f0-c1e5-11e5-96ce-806980b39519.png">

**Comment by havvg** [comment]
This has been done with Symfony 2.8.2 and PropelBundle 1.5.x-dev.

**Comment by havvg** [comment]
One step is missing, sorry about it. You have to remove the generated classes, that are not `om`, `map`. within `src/Propel`

**Comment by havvg** [comment]
Those steps are only required, if you want to check-in the files under version control. Otherwise, the acl:init should be run on deployments.

**Comment by havvg** [comment]
<img width="1280" alt="screen shot 2016-01-23 at 20 50 20" src="https://cloud.githubusercontent.com/assets/126898/12532377/fc43edc0-c212-11e5-86b0-78f87bc410ff.png">

The new setup results in this workflow. I'm closing this issue as the 1.5 versions will be released soonish :)
