### ISSUE TITLE
A successful query with multiple and conditions requires this one weird trick

### ISSUE THREAD

**Issue by tayhimself** [propelorm/PropelBundle#344]
There is some strangeness in the propel query generator that I'd like to point out.  Using propel 1.x, trying to have multiple **and** conditions.
I hope this is helpful to the dev team if it is an issue. If it isn't an explanation of my confusion would be awesome. Thx!
 
### Problem query 
The problem is that the the _s2_ condition which i want to be **AND** instead becomes part of the **OR**.

                      ->useSurveyQuery()
                        ->condition('s1', 'survey.Type ="Baseline" OR survey.Type="Yearly" OR survey.Type="Monthly"')
                        ->condition('s2', 'survey.complete=1')
                        ->condition('s3', 'survey.created_at < "2015-06-28"') // year 2 only
                        ->where(array('s1', 's2', 's3'),'and')
                      ->endUse()

results in the following SQL (again only relevant part shown)

     AND ((survey.type ="Baseline" OR survey.type="Yearly" OR survey.type="Monthly" AND survey.complete=1) AND survey.created_at < "2015-06-28")

### Weird fix query 
Notice the extra brackets added by the _filler_ condition which is always true that moves _s2_ outside the brackets so that it is not part of the _s1_ or conditions. 

                      ->useSurveyQuery()
                        ->condition('s1', 'survey.Type ="Baseline" OR survey.Type="Yearly" OR survey.Type="Monthly"')
                        ->condition('filler', 'survey.id is not null')
                        ->condition('s2', 'survey.complete=1')
                        ->condition('s3', 'survey.created_at < "2015-06-28"') // year 2 only
                        ->where(array('s1', 'filler', 's2', 's3'),'and')
                      ->endUse()

results in the following SQL (again only relevant part shown)

        AND (((survey.type ="Baseline" OR survey.type="Yearly" OR survey.type="Monthly" AND survey.id is not null) AND survey.complete=1) AND survey.created_at < "2015-06-28")

**Comment by havvg** [comment]
Hi, thanks for the issue, could you please report it on the https://github.com/propelorm/Propel repository?
