### ISSUE TITLE
identifierQuoting does not work with propel:fixtures:dump

### ISSUE THREAD

**Issue by Hadrien45** [propelorm/PropelBundle#361]
Hi, 

I use MySQL, according to the documentation, I use the identifierQutoting in my schema.xml because my table name is "group".
When I launch a propel:fixtures:dump, an SQL error appears. 
In file AbstractDataDumper.php (https://github.com/propelorm/PropelBundle/blob/2.0/DataFixtures/Dumper/AbstractDataDumper.php#L110), the query is 
<code>SELECT * FROM group</code> whereas it should be <code>SELECT * FROM \`group\`</code>.

Thanks

**Comment by havvg** [comment]
Just verified it's working with 1.5.

**Comment by Hadrien45** [comment]
Hi, thanks for your answer. I try with "propel/propel-bundle": "~2.0@dev" and it's work.
