### ISSUE TITLE
propel:sql:build creates sql file outside cache, but reports different location

### ISSUE THREAD

**Issue by Gamesh** [propelorm/PropelBundle#376]
might be related to #307.
when you run console `propel:sql:build` propel dumps a map and sql into the `app/propel/sql` (which is a weird place if you ask me, because the schema and everything related is located in the bundle), but reports files being added to cache folder.
output:
```
 ../sf/bin/console propel:sql:build
>>  File+    /home/vagrant_data/dev/sf/var/cache/dev/sql/ituvs.sql
>>  File+    /home/vagrant_data/dev/sf/var/cache/dev/sql/sqldb.map
1 SQL file has been generated.
```
it reports that files were created in the cache/<env>, but places them in the app/propel/sql folder.

**Comment by havvg** [comment]
I'm assuming, you are using Propel2?

**Comment by Gamesh** [comment]
no i'm using propel v1.7.1 as propel2 does not have a stable release yet
