### ISSUE TITLE
[RFC] rename namespace to Propel\Bundle\PropelBundle

### ISSUE THREAD

**Issue by havvg** [propelorm/PropelBundle#385]
I'm on the `PropelAclBundle` (https://github.com/havvg/PropelAclBundle, as mentioned in #343), which integrates the ACL component with Propel without the hassle you are required to take when using the current version. It makes it a lot easier.

As this will be the second Symfony bundle providing some sort of integration with Propel, I would like to rename the namespace to `Propel\Bundle\PropelBundle` and the new bundle will be created at `Propel\Bundle\PropelAclBundle`. Feedback welcome!

As the 1.5 branch of this bundle has no tagged version yet, I would like to introduce it with the `v1.5.0` which will also suggest the `PropelAclBundle` and will also remove the current implementation from this bundle.

Your thoughts? 

@propelorm It would be awesome if someone could create the repository for the `PropelAclBundle` and grant me access to it :)

**Comment by marcj** [comment]
Created, +1 :)

**Comment by havvg** [comment]
Thanks @marcj could you enable it on travis, too? Now there is code.

**Comment by havvg** [comment]
.. and composer :)
