### ISSUE TITLE
Deprecation issues with ModelType

### ISSUE THREAD

**Issue by tjveldhuizen** [propelorm/PropelBundle#394]
Using the ModelType results in some deprecated warnings. Are there plans to fix them? I tried thinking out a pull request, but can't manage to decide on the correct procedure concerning backwards compatibilty and so on. (I'm using the 1.5-branch)
- Accessing type "choice" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\ChoiceType" instead.
- Propel\Bundle\PropelBundle\Form\Type\ModelType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0.
- The Symfony\Component\Form\Extension\Core\ChoiceList\ObjectChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.
- The Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.
- The Propel\Bundle\PropelBundle\Form\ChoiceList\ModelChoiceList class extends Symfony\Component\Form\Extension\Core\ChoiceList\ObjectChoiceList that is deprecated since Symfony 2.7, to be removed in version 3.0. Use {@link \Symfony\Component\Form\ChoiceList\ArrayChoiceList} instead.
- The value "false" for the "choices_as_values" option of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.8 and will not be supported anymore in 3.0. Set this option to "true" and flip the contents of the "choices" option instead.
- The "choice_list" option of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.7 and will be removed in 3.0. Use "choice_loader" instead.
- The Symfony\Component\Form\Extension\Core\View\ChoiceView class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\View\ChoiceView instead.

**Comment by havvg** [comment]
The PR should be against the 1.5 branch, as the 1.6 will be opened based on the release of `v1.5.0`. The code should use the new (3.0+) methods, but support 2.8. Whereas the 1.6 branch will remove the support as it will require 3.0.

**Comment by jusurb** [comment]
@havvg any plans for porting some of this code to branch 1.6, to support sf 3 ? cause now branch 1.6 is not usable with sf 3

**Comment by marcj** [comment]
I guess this will not happen as it not that easy and 1.6 userbase shrinks.

**Comment by jusurb** [comment]
that's too bad, maybe docs should remove that 1.6 branch support sf 3 as it clearly does not currently, at-least not fully
