### ISSUE TITLE
Namespace maintenance?

### ISSUE THREAD

**Issue by lionelbzv** [propelorm/PropelBundle#400]
In order to continue using the default configuration of the FOSUserBundle, "the PropelBundle should maintain the old constraint namespace as long as they are not bumping the major version".

see https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2068

**Comment by stof** [comment]
Actually, you should maintain backward compatibility as long you don't bump the major version (which means you should follow semver)

**Comment by havvg** [comment]
This has been fixed in https://github.com/propelorm/PropelBundle/releases/tag/1.5.1
