### ISSUE TITLE
PropelBundle 1.6 branch throws exceptions for the Symfony 3 Profiler integration

### ISSUE THREAD

**Issue by niels-nijens** [propelorm/PropelBundle#401]
Usage of the render function has (apparently) changed in Symfony 3. The propel.html.twig uses 2 render calls that need to be changed from `{% %}` to `{{  }}`.

Also the `PanelController extends ContainerAware`. The `ContainerAware` class has been removed in Symfony 3 and should be changed to `implements ContainerAwareInterface` and use the `ContainerAwareTrait`.

I can provide a PR if you want.

**Comment by marcj** [comment]
I'm not sure if @havvg is already working on it, but if not we'd love to see a pull-request. waiting for @havvg feedback.

**Comment by havvg** [comment]
PRs are very welcome. I only created the 1.6 branch, there are no changes made to actually work with Symfony 3.0 - it's on schedule, but I didn't do anything so far. I will backport the changes from the 2.0 branch into 1.6 this weekend. Any help is welcome :)

**Comment by niels-nijens** [comment]
Alright, I will supply a PR tomorrow with the fixes I've made to get Propel panel to work within the profiler.

**Comment by marcj** [comment]
Yeah cool :)
