### ISSUE TITLE
2.x Branch and Symfony 2.8|3.0

### ISSUE THREAD

**Issue by immutef** [propelorm/PropelBundle#404]
You recently changed the Symfony constraint up from 2.x to 2.8|3.0 - we're using the Bundle and Propel version 2.x in our projects (about 20) for almost 1.5 years now (thanks to help of @marcj) - but with the bold move to raise the Symfony version to at least 2.8 we're forced to upgrade some older projects if we want to receive further updates (which we want to receive).

Could you think of lowering the constraint to at least 2.7? Or is there any decision I've missed to no longer support that version?

At least you could've started a 3.0 branch for Symfony 2.8|3.0 and keep a 2.x branch for Symfony <2.8. Although Propel2 & Bundle is still alpha, that was a kick in the guts.

**Comment by havvg** [comment]
Thanks for the head-up. It wasn't an easy decision. The main point on putting `2.8` in favor of `2.7` is the least difference to `3.0` with the bundle being alpha in this state.

I will re-visit the changes between 2.7 and 2.8 and reconsider the version constraint!

**Comment by immutef** [comment]
Yeah, but Symfony 3.0 is a new major version (even if 2.8 is compatible). Why not bump this bundle to another major version (3.0) and keep the 2.0 for Symfony 2.x? ;-)

**Comment by marcj** [comment]
If there aren't too much bc breaks PropelBundle needs to deal with there's no need to create yet another branch.

**Comment by marcj** [comment]
PropelBundle couldn't work with 3.0 and <3.0 at the same time. I've reverted all Symfony 3.0 and 2.8 changes in the 2.0 branch and moved those changes to 3.0 branch, so you should be able to keep using PropelBundle with Symfony <2.8 now.

**Comment by immutef** [comment]
Thanks mate! :clap:
