### ISSUE TITLE
Unrecognized option "model_paths" under "propel.database.connections.default"

### ISSUE THREAD

**Issue by Hadrien45** [propelorm/PropelBundle#409]
Hi, 
I use Propel2 and PropelBundle in Symfony 2.8.4.
I launch a symfony command to generate models

<pre>
php app/console propel:model:build
</pre>

, I have this "Unrecognized option "model_paths" under "propel.database.connections.default" "

My config.yml file

<pre>
propel:
    database:
        connections:
            default:
                adapter:    mysql
                user:       %database_user%
                password:   %database_password%
                dsn:        mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
    runtime:
        defaultConnection: default
    generator:
        defaultConnection: default
</pre>

My composer file

<pre>
...
"propel/propel": "2.0.*@dev",
"propel/propel-bundle": "~2.0@dev",
...
</pre>

Any ideas ?

Thanks.

**Comment by marcj** [comment]
Seems like latest commit https://github.com/propelorm/PropelBundle/commit/91e930fedcf13f0ec89cded05177baff1eb4738c broke something. @havvg @thomaschaaf

**Comment by havvg** [comment]
It looks like the required changes in Propel2 are missing? https://github.com/propelorm/Propel2/pull/1125

**Comment by Hadrien45** [comment]
I close this issue because propelorm/Propel2#1125 was merged. 
I've updated composer and the commands work again. 

Thanks

**Comment by marcj** [comment]
@havvg you were right :D :smile:
