### ISSUE TITLE
Skip processing of third-party schemas

### ISSUE THREAD

**Issue by ghost** [propelorm/PropelBundle#433]
Hey,

thanks for this awesome bundle. Is it possible to skip processing of third-party schemas?

I'm using the 3.0.x-dev branch and fos/oauth-server-bundle which has a schema.xml which uses `typehintable` behaviour from @willdurand.

So, my model build process is failing:

```
$ php app/console propel:model:build -vvv
Processing: BusinessBundle-schema.xml
  5 tables processed successfully
Processing: FOSOAuthServerBundle-schema.xml

[Propel\Generator\Exception\BehaviorNotFoundException]
Unknown behavior "typehintable". You may try running `composer update` or passing the `--composer-dir` option.
```

There seems to be a `bundle` command line arg:

`propel:model:build [--platform [PLATFORM]] [--connection [CONNECTION]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<bundle>]`

Anyway, if I run `php app/console propel:model:build BusinessBundle` he also tries to processing the schema.xml from fos/oauth-server-bundle and fos/user-bundle.

Best,
Christian

**Comment by dereuromark** [comment]
All propel2 dev should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the successor project of this now.
