### ISSUE TITLE
Hardcoded schema path

### ISSUE THREAD

**Issue by patie** [propelorm/PropelBundle#446]
There are hardcoded paths for schema

-  https://github.com/propelorm/PropelBundle/blob/3.0/DependencyInjection/PropelExtension.php#L54
- https://github.com/propelorm/PropelBundle/blob/3.0/Service/SchemaLocator.php#L43

unfortunelly this is not good i think, especially when programmer dont use bundles, there is no easy way to set path without Resources/config suffix

**Comment by marcj** [comment]
When you don't use bundles, why would you want to use PropelBundle?

**Comment by patie** [comment]
@marcj i mean im not using bundles in src, of course im using 3rd party bundles (vendors)
