### ISSUE TITLE
YAML files parsed in production

### ISSUE THREAD

**Issue by gharlan** [propelorm/PropelBundle#448]
In my app blackfire.io gives me this recommendation:

![screenshot 2017-02-24 18 00 53](https://cloud.githubusercontent.com/assets/330436/23312764/34cb30a4-fabb-11e6-86e4-a3a7803d1758.png)

The yaml parsings are caused by this line:
https://github.com/propelorm/PropelBundle/blob/3.0/Request/ParamConverter/PropelParamConverter.php#L107

This part was added in #245 (ping @havvg).

I'm not sure, how we could "fix" it.

**Comment by marcj** [comment]
AFAIK `router->getRouteCollection` always hits the raw actual config files since it's not cached (only its build routes urls). There's afaik no built-in solution to get a list of all `Route` instances.

**Comment by gharlan** [comment]
https://github.com/symfony/symfony/issues/11171

So maybe we should move the `propel_converter` into `defaults`?
