### ISSUE TITLE
[1.6] Wrong allowedTypes

### ISSUE THREAD

**Issue by nibsirahsieu** [propelorm/PropelBundle#466]
https://github.com/propelorm/PropelBundle/blob/e10bb77cb823448ce648ca2c1127b5421f3c8071/Form/Type/ModelType.php#L245

it should be \ModelCriteria

**Comment by nibsirahsieu** [comment]
ping @jaugustin

**Comment by jaugustin** [comment]
@nibsirahsieu good catch it's fixed ;) but we should add tests for this class

**Comment by nibsirahsieu** [comment]
👍 .  One more, it's seem you forgot to backport the [PropelExtension.php](https://github.com/propelorm/PropelBundle/blob/3.0/Form/PropelExtension.php) class

**Comment by jaugustin** [comment]
@nibsirahsieu the current code seems ok. I didn't test it with a real use case.

Do we have any issue with the current 1.6 ?

**Comment by nibsirahsieu** [comment]
i haven't tried it yet, i'm still using my own fork. But after reading the code, nothing wrong actually. Both of them are valid.
