### ISSUE TITLE
Symfony 4.x compatibility 

### ISSUE THREAD

**Issue by davyrolink** [propelorm/PropelBundle#479]
I just tried to upgrade to Symfony 4, but the PropelBundle isn't compatible. Composer runs the "cache:clear"-command which fails with the error below. Probably there will be more compatibility issues.

```
PHP Fatal error:  Class Propel\Bundle\PropelBundle\DataCollector\PropelDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset) in .../vendor/propel/propel-bundle/DataCollector/PropelDataCollector.php on line 24
```

**Comment by dereuromark** [comment]
All propel2 dev should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the successor project of this now.
