### ISSUE TITLE
Symfony 3.4 Flex `The "propel.logger" service is private` deprecation notice

### ISSUE THREAD

**Issue by ldath** [propelorm/PropelBundle#481]
Hi,

PropelBundle have issues with the Symfony 3.4 when running functional tests:

```
The "propel.logger" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead: 1x
    1x in DefaultControllerTest::testIndex from App\Tests\Controller
```

**Comment by hsashi** [comment]
"propel/propel-bundle/Resources/config/propel.xml"

please try public="true"
don't forget cache:clear!

          <service id="propel.logger" class="%propel.logger.class%" public="true">
             <tag name="monolog.logger" channel="propel" />
             <argument type="service" id="logger" on-invalid="null" />
             <argument type="service" id="debug.stopwatch" on-invalid="null" />
         </service>

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
