### ISSUE TITLE
Tag for branch 4.0

### ISSUE THREAD

**Issue by eugenekurasov** [propelorm/PropelBundle#484]
Hi,

For symfony 4+ you already have branch 4.0 but not have tag.
@marcj can you add tag?

**Comment by eugenekurasov** [comment]
ping @marcj

**Comment by Bukashk0zzz** [comment]
@marcj Please)

**Comment by ft-1408** [comment]
ping @marcj

**Comment by svitiashchuk** [comment]
@marcj Please) [2]

**Comment by marcj** [comment]
Well, tagging means adding semantical version with coverage BC etc. You can already use it via branch name in composer. json, can't you?

**Comment by Bukashk0zzz** [comment]
Need to update bundle https://github.com/lexik/LexikTranslationBundle/pull/294
And set correct version. Use branch in bundle not good idea.

**Comment by Bukashk0zzz** [comment]
@marcj So what you plan to do? Is there any chance to add tag?
