### ISSUE TITLE
3.0 Update propel/propel to allow use of latest alpha

### ISSUE THREAD

**Issue by josefguenther** [propelorm/PropelBundle#489]
The current release (3.0.0-alpha1) does not track the latest propel alpha.

`"propel/propel": "2.0.0-alpha6"` should be either updated to `alpha8` or updated to track the latest alpha.

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
