### ISSUE TITLE
FileLocator issue on PropelBundle 4.0

### ISSUE THREAD

**Issue by pimpreneil** [propelorm/PropelBundle#490]
Hi,

I have an issue when using PropelBundle 4.0 on a Symfony 3.4: The schema won't build: I have the following error:

    The file "MyMasterBundleMySubBundle/Resources/config/schema.xml" does not exist...

After a deeper look, I have noticed that you have removed the '@' in the transformToLogicalName method of Service/SchemaLocator.php and that it is causing my error.

I don't know Symfony 3.4 and 4.0 well enough to figure out if you did this on purpose to address a future deprecation, but I am still raising an issue here as Symfony's FileLocator is still looking for a heading '@' for bundle files: https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/HttpKernel/Config/FileLocator.php#L48

_Note : I know that I should not use sub-bundles nor custom bundle names but well I don't want to change for now and I hope I won't have to do it to fix this issue!_

Thanks for your help

**Comment by nibsirahsieu** [comment]
second on this. When running `php bin/console propel:model:build --verbose`, i got this error

`
[Symfony\Component\Config\Exception\FileLocatorFileNotFoundException]
  The file "AppBundle/Resources/config/schema.xml" does not exist (in: /Users/yunannsnt/webdev/SymfonyStarter-3.4/app, /Users/yunannsnt/webdev/SymfonyStarter-3.4/app/Resources
  ).
`

**Comment by sanders54** [comment]
Same issue here. Above commit would probably do the trick.

**Comment by HungryJackOConnell** [comment]
in `app/config/config.yml `

propel:
&nbsp;&nbsp;&nbsp;&nbsp;paths:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;schemaDir: '%kernel.project_dir%/src'

thanks cristianoc72 for [this doc](https://gist.github.com/cristianoc72/9060420#file-propel-yaml-L17)

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
