### ISSUE TITLE
sluggable behavior: FatalThrowableError - Unsupported operand types

### ISSUE THREAD

**Issue by icyevilfantasy** [propelorm/PropelBundle#492]
i'm getting a FatalThrowableError through `Unsupported operand types` while using the sluggable behavior. 

![image](https://user-images.githubusercontent.com/695350/38572434-6754c1d6-3cf3-11e8-95b9-f75316f542cb.png)

This error occurs only if i have duplicate titles, so that the behavior have to modify the slug with a number.

### i'm using

![image](https://user-images.githubusercontent.com/695350/38572706-275c1682-3cf4-11e8-8f30-a7191d2f4bc5.png)

### my schema

![image](https://user-images.githubusercontent.com/695350/38572087-667308be-3cf2-11e8-9e14-4d2f40730b32.png)

### problematic code in base class
    
at the end of `protected function makeSlugUnique(...){ ... }`

![image](https://user-images.githubusercontent.com/695350/38572157-9b8f5304-3cf2-11e8-8898-5a52abc7f6da.png)

### my temporary solution

![image](https://user-images.githubusercontent.com/695350/38572185-b376bdae-3cf2-11e8-9ace-b42adfdecce5.png)

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
