### ISSUE TITLE
 Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by Ghaidan98** [propelorm/PropelBundle#499]
if(isset($_POST['uid']) && isset($_POST['cname']) && isset($_POST['uname']) && isset($_POST['pass']) && isset($_POST['country']) && isset($_POST['email'])&& isset($_POST['date']) && isset($_POST['phone']) && isset($_POST['register'])){
		$sql="INSERT INTO customers (uid, cname, uname, pass, country, email, date, phone) VALUES (:ui,:cn,:un,:pa,:co,:em,:da,:ph)";
		$stmt = $conn-> prepare($sql);
		if($stmt !== false) {
		$stmt->execute(array(
		':ui' => $_POST['uid'],
		':cn' => $_POST['cname'],
		':un' => $_POST['uname'],
		':pa' => encrypt($_POST['pass']),
		':co' => $_POST['country'],
		':em' => $_POST['email'],
		':da' => $_POST['date'],
		':ph' => $_POST['phone']));
		}
		else
		header("Location:index.php");
	}

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
