### ISSUE TITLE
Cannot require branch 4.0?

### ISSUE THREAD

**Issue by rayrigam** [propelorm/PropelBundle#501]
I'm trying to require the PropelBundle branch 4.0 in my composer.json file using: `"propel/propel-bundle": "4.0.*@dev"`.  However, I get an error when running "compose update":

> Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package propel/propel-bundle 4.0.*@dev exists as propel/propel-bundle[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0.0, 1.0.x-dev, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.x-dev, 1.2.0, 1.2.1, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.x-dev, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.x-dev, 1.5.0, 1.5.1, 1.5.2, 1.5.x-dev, 1.6.x-dev, 2.0.0-alpha4, 2.0.x-dev, 3.0.0-alpha1, 3.0.x-dev, dev-master] but these are rejected by your constraint. 

I tried other ways, such as specifying the latest commit, but it does not work. In [packagist](https://packagist.org/packages/propel/propel-bundle), the branch 4.0 does not show up. Could this be fixed? Otherwise, could you suggest how to require that branch?

**Comment by david-fanin** [comment]
Hello,
I also get the same error when trying to install a new dependency. It seems that the version "4.0.*@dev" has been deleted. Maybe by mistake? Is it possible to correct this?
Thank you!

**Comment by rayrigam** [comment]
@david-fanin where you able to somehow install the branch 4.0? If so, could you share how?

**Comment by rayrigam** [comment]
I found a way to require github repositories that are not in packagist using this reference: [https://getcomposer.org/doc/05-repositories.md#vcs](https://getcomposer.org/doc/05-repositories.md#vcs)
And was able to require [this pull request](https://github.com/propelorm/PropelBundle/pull/491), which works so far with Symfony 4.0 using the following in my composer.json file:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cristianoc72/PropelBundle"
        }
    ],
    "require": {
        "propel/propel": "2.0.*@dev",
        "propel/propel-bundle": "~4.0@dev",
     }
```

**Comment by nibsirahsieu** [comment]
Thanks @rayrigam it works.

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
