### ISSUE TITLE
branch 3.0 PropelDataCollector cloneVar bug using Symfony 2.8-3.1

### ISSUE THREAD

**Issue by kasparsj** [propelorm/PropelBundle#502]
PropelDataCollector uses `cloneVar` which was introduced in Symfony 3.2.
That makes 3.0 branch only starting Symfony 3.2.

**Comment by dereuromark** [comment]
All further dev and tickets should go into https://github.com/SkyFoxvn/PropelBundle as this will most likely be the follower of this now.
